--- 
env: 
  browser: true
  node: true
  jest: true
extends: airbnb
parser: babel-eslint
plugins: 
  - prettier
  - jest
rules: 
  arrow-body-style: 
    - 2
    - as-needed
  no-await-in-loop: 
    - 1
